name: Angle-ish
analytics: {}
purpose: []
github: true
author:
  name: 'Roland Tanglao '
cta: {}
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
content: []
navigation:
  - type: external
    name: roland
    url: 'http://rolandtanglao.com'
layout_spectrum: 0.9425349
color:
  lightness: 1
  brandColors:
    - '#6b6b6b'
    - '#8b8b8b'
    - '#010101'
    - '#323232'
    - '#dedede'
  saturation: 1
  brandStrength: 0.8125
  rhythmicContrast: 1
content_rating:
  adult: false
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/eca4671b-ff42-4564-915b-91cf6fd741c3.jpg
typography_spectrum: 0.1414886314887553
opengraph: {}
title: life is too short for straightforwardness
